# Generated by Django 3.1.7 on 2021-04-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('model_name', models.CharField(max_length=80)),
                ('spec', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=120)),
                ('img', models.ImageField(upload_to='images')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.brands')),
            ],
        ),
    ]
